package chat;


/**
* chat/Chat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, April 23, 2018 12:05:42 PM EET
*/

public interface Chat extends ChatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chat
