package chat;


/**
* chat/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Sunday, April 22, 2018 11:23:42 PM GMT+02:00
*/

public interface ChatOperations 
{
  String connect ();
  void sendMessage (String token, String message);
  String receiveMessage (String token);
  boolean createChatRoom (String token, String name);
  boolean listChatRooms (String token);
  boolean joinChatRoom (String token, String name);
  boolean leaveChatRoom (String token);
  boolean changeName (String token, String name);
  String getName (String token);
} // interface ChatOperations
