package chat;

/**
* chat/ChatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, April 23, 2018 12:05:42 PM EET
*/

public final class ChatHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.Chat value = null;

  public ChatHolder ()
  {
  }

  public ChatHolder (chat.Chat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ChatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ChatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ChatHelper.type ();
  }

}
