package chat;


/**
* chat/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 25, 2018 9:39:15 PM EET
*/

public interface ChatOperations 
{
  String getToken ();
  void sendMessage (chat.Message msg);
  boolean roomType (chat.User user);
  String getRoom (chat.User user);
  boolean getRoomType (chat.User user);
  String getMessage (chat.User user);
  boolean createChatRoom (chat.Room room);
  String listChatRooms ();
  boolean joinChatRoom (chat.User user, chat.Room room);
  boolean leaveChatRoom (chat.User user);
  boolean changeName (chat.User user);
  String getName (chat.User user);
} // interface ChatOperations
