package chat;


/**
* chat/ChatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, April 23, 2018 10:25:27 PM EET
*/

public abstract class ChatPOA extends org.omg.PortableServer.Servant
 implements chat.ChatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("connect", new java.lang.Integer (0));
    _methods.put ("sendMessage", new java.lang.Integer (1));
    _methods.put ("receiveMessage", new java.lang.Integer (2));
    _methods.put ("createChatRoom", new java.lang.Integer (3));
    _methods.put ("listChatRooms", new java.lang.Integer (4));
    _methods.put ("joinChatRoom", new java.lang.Integer (5));
    _methods.put ("leaveChatRoom", new java.lang.Integer (6));
    _methods.put ("changeName", new java.lang.Integer (7));
    _methods.put ("getName", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/Chat/connect
       {
         String $result = null;
         $result = this.connect ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // chat/Chat/sendMessage
       {
         String token = in.read_string ();
         String message = in.read_string ();
         this.sendMessage (token, message);
         out = $rh.createReply();
         break;
       }

       case 2:  // chat/Chat/receiveMessage
       {
         String token = in.read_string ();
         String $result = null;
         $result = this.receiveMessage (token);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // chat/Chat/createChatRoom
       {
         String token = in.read_string ();
         String name = in.read_string ();
         boolean $result = false;
         $result = this.createChatRoom (token, name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // chat/Chat/listChatRooms
       {
         String token = in.read_string ();
         String $result = null;
         $result = this.listChatRooms (token);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // chat/Chat/joinChatRoom
       {
         String token = in.read_string ();
         String name = in.read_string ();
         boolean $result = false;
         $result = this.joinChatRoom (token, name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // chat/Chat/leaveChatRoom
       {
         String token = in.read_string ();
         boolean $result = false;
         $result = this.leaveChatRoom (token);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // chat/Chat/changeName
       {
         String token = in.read_string ();
         String name = in.read_string ();
         boolean $result = false;
         $result = this.changeName (token, name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // chat/Chat/getName
       {
         String token = in.read_string ();
         String $result = null;
         $result = this.getName (token);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/Chat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Chat _this() 
  {
    return ChatHelper.narrow(
    super._this_object());
  }

  public Chat _this(org.omg.CORBA.ORB orb) 
  {
    return ChatHelper.narrow(
    super._this_object(orb));
  }


} // class ChatPOA
