package chat;


/**
* chat/Room.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 25, 2018 12:24:11 PM EET
*/

public final class Room implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  public Room ()
  {
  } // ctor

  public Room (String _name)
  {
    name = _name;
  } // ctor

} // class Room
