package chat;

/**
* chat/RoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 25, 2018 12:24:11 PM EET
*/

public final class RoomHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.Room value = null;

  public RoomHolder ()
  {
  }

  public RoomHolder (chat.Room initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.RoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.RoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.RoomHelper.type ();
  }

}
