package chat;

/**
* chat/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 25, 2018 9:39:15 PM EET
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (chat.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.UserHelper.type ();
  }

}
